"""builds

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-23 22:44:14.042181
"""
from __future__ import annotations

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = '0002'
down_revision = '0001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('builds',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('engine', sa.String(length=16), nullable=False),
    sa.Column('includeonly', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('seconds', sa.Float(), nullable=False),
    sa.Column('diagnostics', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('figures', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('log', sa.Text(), nullable=False),
    sa.Column('pdf_path', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_builds_course_kind', 'builds', ['course_id', 'kind', 'id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_builds_course_kind', table_name='builds')
    op.drop_table('builds')
    # ### end Alembic commands ###
