"""providers and privacy gate

Revision ID: 0003
Revises: 0002
Create Date: 2026-09-23 23:03:46.803599
"""
from __future__ import annotations

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = '0003'
down_revision = '0002'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('approvals',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('job_id', sa.BigInteger(), nullable=True),
    sa.Column('chat_session_id', sa.Integer(), nullable=True),
    sa.Column('request_key', sa.String(length=300), nullable=True),
    sa.Column('provider_id', sa.Integer(), nullable=True),
    sa.Column('model', sa.String(length=200), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('decision', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tokens_estimate', sa.BigInteger(), nullable=False),
    sa.Column('cost_estimate', sa.Float(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approvals_job_id'), 'approvals', ['job_id'], unique=False)
    op.create_index('ix_approvals_job_key', 'approvals', ['job_id', 'request_key'], unique=False)
    op.create_index('ix_approvals_status', 'approvals', ['status', 'id'], unique=False)
    op.create_table('audit_log',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=True),
    sa.Column('provider_name', sa.String(length=100), nullable=False),
    sa.Column('provider_type', sa.String(length=30), nullable=False),
    sa.Column('is_local', sa.Boolean(), nullable=False),
    sa.Column('model', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=40), nullable=True),
    sa.Column('task', sa.String(length=80), nullable=True),
    sa.Column('request_key', sa.String(length=300), nullable=True),
    sa.Column('payload_sha256', sa.String(length=64), nullable=False),
    sa.Column('payload_path', sa.Text(), nullable=True),
    sa.Column('response_sha256', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('tokens_in', sa.BigInteger(), nullable=False),
    sa.Column('tokens_out', sa.BigInteger(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('approval_id', sa.BigInteger(), nullable=True),
    sa.Column('authorization', sa.String(length=40), nullable=True),
    sa.Column('job_id', sa.BigInteger(), nullable=True),
    sa.Column('chat_session_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_job_key', 'audit_log', ['job_id', 'request_key'], unique=False)
    op.create_index('ix_audit_ts', 'audit_log', ['ts'], unique=False)
    op.create_table('prompts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key', 'version')
    )
    op.create_index(op.f('ix_prompts_key'), 'prompts', ['key'], unique=False)
    op.create_table('providers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('base_url', sa.Text(), nullable=True),
    sa.Column('api_key_enc', sa.Text(), nullable=True),
    sa.Column('is_local', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('zdr', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('zdr_notes', sa.Text(), nullable=True),
    sa.Column('models', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('last_test', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('session_grants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_session_id', sa.Integer(), nullable=False),
    sa.Column('login_session_id', sa.String(length=64), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('refs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_session_grants_chat_session_id'), 'session_grants', ['chat_session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_session_grants_chat_session_id'), table_name='session_grants')
    op.drop_table('session_grants')
    op.drop_table('providers')
    op.drop_index(op.f('ix_prompts_key'), table_name='prompts')
    op.drop_table('prompts')
    op.drop_index('ix_audit_ts', table_name='audit_log')
    op.drop_index('ix_audit_job_key', table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index('ix_approvals_status', table_name='approvals')
    op.drop_index('ix_approvals_job_key', table_name='approvals')
    op.drop_index(op.f('ix_approvals_job_id'), table_name='approvals')
    op.drop_table('approvals')
    # ### end Alembic commands ###
