"""ingestion and review

Revision ID: 0004
Revises: 0003
Create Date: 2026-09-23 23:22:48.850436
"""
from __future__ import annotations

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = '0004'
down_revision = '0003'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inbox_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('language', sa.String(length=8), nullable=True),
    sa.Column('job_id', sa.BigInteger(), nullable=True),
    sa.Column('bundle', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('guesses', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('source_file_ids', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('assigned_job_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_inbox_status', 'inbox_items', ['status', 'id'], unique=False)
    op.create_table('ingest_figures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.BigInteger(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('key', sa.String(length=60), nullable=False),
    sa.Column('origin', sa.String(length=20), nullable=False),
    sa.Column('source_ref', sa.Text(), nullable=False),
    sa.Column('crop_blob', sa.String(length=64), nullable=True),
    sa.Column('code_text', sa.Text(), nullable=True),
    sa.Column('bbox', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('description_ref', sa.Text(), nullable=True),
    sa.Column('classification', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('code', sa.Text(), nullable=True),
    sa.Column('latex_inline', sa.Text(), nullable=True),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('render_blob', sa.String(length=64), nullable=True),
    sa.Column('iterations', sa.Integer(), nullable=False),
    sa.Column('log', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('group_key', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'key')
    )
    op.create_index(op.f('ix_ingest_figures_job_id'), 'ingest_figures', ['job_id'], unique=False)
    op.create_table('ingest_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.BigInteger(), nullable=False),
    sa.Column('upload_id', sa.Integer(), nullable=False),
    sa.Column('source_file_id', sa.Integer(), nullable=False),
    sa.Column('page', sa.Integer(), nullable=True),
    sa.Column('key', sa.String(length=40), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('kind_source', sa.String(length=10), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('latex', sa.Text(), nullable=True),
    sa.Column('annotations', sa.Text(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('image_blob', sa.String(length=64), nullable=True),
    sa.Column('preview_blob', sa.String(length=64), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('language', sa.String(length=8), nullable=True),
    sa.Column('group_key', sa.String(length=40), nullable=True),
    sa.Column('excluded', sa.Boolean(), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'key')
    )
    op.create_index(op.f('ix_ingest_items_job_id'), 'ingest_items', ['job_id'], unique=False)
    op.create_index(op.f('ix_ingest_items_upload_id'), 'ingest_items', ['upload_id'], unique=False)
    op.create_table('proposals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('job_id', sa.BigInteger(), nullable=True),
    sa.Column('chat_session_id', sa.Integer(), nullable=True),
    sa.Column('chapter_id', sa.Integer(), nullable=True),
    sa.Column('new_chapter_title', sa.Text(), nullable=True),
    sa.Column('new_chapter_position', sa.Integer(), nullable=True),
    sa.Column('sources', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('source_file_ids', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('figures', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('warnings', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('compile_status', sa.String(length=20), nullable=True),
    sa.Column('diagnostics', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('preview_pdf_blob', sa.String(length=64), nullable=True),
    sa.Column('revision_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proposals_course_id'), 'proposals', ['course_id'], unique=False)
    op.create_index('ix_proposals_status', 'proposals', ['status', 'id'], unique=False)
    op.create_table('proposal_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proposal_id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(length=300), nullable=False),
    sa.Column('op', sa.String(length=10), nullable=False),
    sa.Column('base_blob', sa.String(length=64), nullable=True),
    sa.Column('new_text', sa.Text(), nullable=True),
    sa.Column('new_blob', sa.String(length=64), nullable=True),
    sa.Column('edits', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.ForeignKeyConstraint(['proposal_id'], ['proposals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proposal_files_proposal_id'), 'proposal_files', ['proposal_id'], unique=False)
    op.create_table('uploads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('target_course_id', sa.Integer(), nullable=True),
    sa.Column('target_chapter_id', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('job_id', sa.BigInteger(), nullable=True),
    sa.Column('file_count', sa.Integer(), nullable=False),
    sa.Column('total_size', sa.BigInteger(), nullable=False),
    sa.Column('via', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['target_chapter_id'], ['chapters.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['target_course_id'], ['courses.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('source_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('upload_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('folder', sa.Text(), nullable=True),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('mime', sa.String(length=100), nullable=True),
    sa.Column('size', sa.BigInteger(), nullable=False),
    sa.Column('blob', sa.String(length=64), nullable=True),
    sa.Column('pages', sa.Integer(), nullable=True),
    sa.Column('language', sa.String(length=8), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['upload_id'], ['uploads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_files_upload_id'), 'source_files', ['upload_id'], unique=False)
    op.create_table('source_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_file_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('chapter_id', sa.Integer(), nullable=True),
    sa.Column('proposal_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_file_id'], ['source_files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_file_id', 'course_id', 'chapter_id')
    )
    op.create_index(op.f('ix_source_links_course_id'), 'source_links', ['course_id'], unique=False)
    op.create_index(op.f('ix_source_links_source_file_id'), 'source_links', ['source_file_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_source_links_source_file_id'), table_name='source_links')
    op.drop_index(op.f('ix_source_links_course_id'), table_name='source_links')
    op.drop_table('source_links')
    op.drop_index(op.f('ix_source_files_upload_id'), table_name='source_files')
    op.drop_table('source_files')
    op.drop_table('uploads')
    op.drop_index(op.f('ix_proposal_files_proposal_id'), table_name='proposal_files')
    op.drop_table('proposal_files')
    op.drop_index('ix_proposals_status', table_name='proposals')
    op.drop_index(op.f('ix_proposals_course_id'), table_name='proposals')
    op.drop_table('proposals')
    op.drop_index(op.f('ix_ingest_items_upload_id'), table_name='ingest_items')
    op.drop_index(op.f('ix_ingest_items_job_id'), table_name='ingest_items')
    op.drop_table('ingest_items')
    op.drop_index(op.f('ix_ingest_figures_job_id'), table_name='ingest_figures')
    op.drop_table('ingest_figures')
    op.drop_index('ix_inbox_status', table_name='inbox_items')
    op.drop_table('inbox_items')
    # ### end Alembic commands ###
