"""retrieval index

Revision ID: 0005
Revises: 0004
Create Date: 2026-09-23 23:45:21.358305
"""
from __future__ import annotations

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy

revision = '0005'
down_revision = '0004'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('index_chunks',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('chapter_id', sa.Integer(), nullable=False),
    sa.Column('heading', sa.Text(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('tsv', postgresql.TSVECTOR(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True),
    sa.Column('model', sa.String(length=200), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_index_chunks_chapter_id'), 'index_chunks', ['chapter_id'], unique=False)
    op.create_index(op.f('ix_index_chunks_course_id'), 'index_chunks', ['course_id'], unique=False)
    op.create_index('ix_index_chunks_tsv', 'index_chunks', ['tsv'], unique=False, postgresql_using='gin')
    op.execute("CREATE INDEX ix_index_chunks_embedding ON index_chunks USING hnsw (embedding vector_cosine_ops)")
    op.create_table('index_state',
    sa.Column('chapter_id', sa.Integer(), nullable=False),
    sa.Column('blob', sa.String(length=64), nullable=False),
    sa.Column('model', sa.String(length=200), nullable=True),
    sa.Column('chunks', sa.Integer(), nullable=False),
    sa.Column('indexed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('chapter_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('index_state')
    op.drop_index('ix_index_chunks_tsv', table_name='index_chunks', postgresql_using='gin')
    op.drop_index(op.f('ix_index_chunks_course_id'), table_name='index_chunks')
    op.drop_index(op.f('ix_index_chunks_chapter_id'), table_name='index_chunks')
    op.drop_table('index_chunks')
    # ### end Alembic commands ###
